/**
 * app.constants used across app
 */
export const CONSTANTS = {

  ELLIPSE: 100,
  SCREEN_HEIGHT: 900,
  SCREEN_WIDTH: 1000,

  /*** enemy config **/
  ENEMY_SLOW_MOVEMENT_SPEED: 1,
  ENEMY_REGULAR_MOVEMENT_SPEED: 2.5,
  ENEMY_FAST_MOVEMENT_SPEED: 5,
  ENEMY_COLOR: '#FF0000',
  SMALL_ENEMY_DIAMETER: 60,
  MEDIUM_ENEMY_DIAMETER: 250,
  BIG_ENEMY_DIAMETER: 500,
}
